export { default as About } from './About'
export { default as Error } from './Error'
export { default as Events } from './Events'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as SingleEvent } from './SingleEvent'
