export const EVENT_SORT_BY = {
  START_DATE: 'startDat',
  END_DATE: 'endDat',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
}

export const EventStatus = {
  SCHEDULED: 'SCHEDULED',
  RIGHT_NOW: 'RIGHT_NOW',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
}

export const EventCategory = {
  MUSIC: 'MUSIC',
  ART_AND_CULTURE: 'ART_AND_CULTURE',
  FOOD_AND_DRINK: 'FOOD_AND_DRINK',
  FAMILY_AND_KIDS: 'FAMILY_AND_KIDS',
  CHARITY: 'CHARITY',
  HEALTH_AND_WELLNESS: 'HEALTH_AND_WELLNESS',
}

export const TicketType = {
  NO_TICKET: 'NO_TICKET',
  GENERAL: 'GENERAL',
  STUDENT: 'STUDENT',
  SENIOR: 'SENIOR',
}
